module.exports = {
  apps: [
    {
      name: "devwonder-fashion",
      script: "server.js", // This file is generated by Next.js standalone build
      instances: "max",
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
    },
  ],
};
